services:
  pgdatabase:
    image: postgres:14
    environment:
      - POSTGRES_USER= root
      - POSTGRES_PASSWORD= root
      - POSTGRES_DB= ny_taxi
    volumes:
      - ./ny-taxi-volume:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL="admin@admin.com"
      - PGADMIN_DEFAULT_PASSWORD="root"
    ports:
      - 8080:80
